---
title: SwingRoller
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  assets:
    title: Assets
    output: false

email:  
description: ""
sass:
  style: compressed
github_username: humont
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
